// <auto-generated />
namespace ArkivaDenis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newmigrationnew88 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newmigrationnew88));
        
        string IMigrationMetadata.Id
        {
            get { return "202010311308147_newmigrationnew88"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
